export const CATALOGO_ITEMS = [
    //Series
    { nombre: "Breaking Bad", tipo: "tv", categoria: "series" },
    { nombre: "Los Hombres De Paco", tipo: "tv", categoria: "series" },
    { nombre: "A Que Estas Esperando", tipo: "tv", categoria: "series" },
    //Novelas Turkas
    { nombre: "Kara Sevda", tipo: "tv", categoria: "novelas" },

    //Novelas Latinas
    { nombre: "Avenida Brasil", tipo: "tv", categoria: "novelas" },
    { nombre: "La Reina del Sur", tipo: "tv", categoria: "novelas" },
    { nombre: "Belleza Fatal", tipo: "tv", categoria: "novelas" },
    { nombre: "La Jefa", tipo: "tv", categoria: "novelas" },
    { nombre: "Las Hijas De La Señora Garcia", tipo: "tv", categoria: "novelas" },
    { nombre: "Los CasaBlanca", tipo: "tv", categoria: "novelas" },
    { nombre: "Sed De Venganza", tipo: "tv", categoria: "novelas" },
    { nombre: "Valle Salvaje", tipo: "tv", categoria: "novelas" },
    { nombre: "Amar, Donde El Amor Teje Sus Redes", tipo: "tv", categoria: "novelas" },
    { nombre: "Amor Amargo", tipo: "tv", categoria: "novelas" },
    { nombre: "Caminos Cruzados", tipo: "tv", categoria: "novelas" },
    { nombre: "Doctora Lucia", tipo: "tv", categoria: "novelas" },
    { nombre: "El Angel de Aurora", tipo: "tv", categoria: "novelas" },
    { nombre: "El Conde Amor y Honor", tipo: "tv", categoria: "novelas" },
    { nombre: "El Precio de Amarte", tipo: "tv", categoria: "novelas" },
    { nombre: "Fugitivas", tipo: "tv", categoria: "novelas" },
    { nombre: "Klass 95", tipo: "tv", categoria: "novelas" },
    { nombre: "La Historia de Juana", tipo: "tv", categoria: "novelas" },
    { nombre: "La Vida Entera", tipo: "tv", categoria: "novelas" },
    { nombre: "Ligeramente Diva", tipo: "tv", categoria: "novelas" },
    { nombre: "Papa Por Conveniencia", tipo: "tv", categoria: "novelas" },
    { nombre: "TIERRA DE DESEOS", tipo: "tv", categoria: "novelas" },
    { nombre: "El Maleficio", tipo: "tv", categoria: "novelas" },
    { nombre: "Golpe de Suerte", tipo: "tv", categoria: "novelas" },
    { nombre: "Marea de Pasiones", tipo: "tv", categoria: "novelas" },
    { nombre: "Nadie Como Tu", tipo: "tv", categoria: "novelas" },
    { nombre: "PACTO DE  SILENCIO", tipo: "tv", categoria: "novelas" },
    { nombre: "Solo Confia", tipo: "tv", categoria: "novelas" },
    { nombre: "Vuelve A Mi", tipo: "tv", categoria: "novelas" },
    { nombre: "ACORRALADA", tipo: "tv", categoria: "novelas" },
    { nombre: "Amar y Vivir", tipo: "tv", categoria: "novelas" },
    { nombre: "AMARTE ASI FRIJOLITO", tipo: "tv", categoria: "novelas" },
    { nombre: "Amor Perfecto", tipo: "tv", categoria: "novelas" },
    { nombre: "Ana de Nadie", tipo: "tv", categoria: "novelas" },
    { nombre: "Anita no te rajes ", tipo: "tv", categoria: "novelas" },
    { nombre: "Buenos dias Veronica", tipo: "tv", categoria: "novelas" },
    { nombre: "CABO", tipo: "tv", categoria: "novelas" },
    { nombre: "Cafe Con Aroma de Mujer ", tipo: "tv", categoria: "novelas" },
    { nombre: "Corran Por Sus Vidas", tipo: "tv", categoria: "novelas" },
    { nombre: "COSITA LINDA", tipo: "tv", categoria: "novelas" },
    { nombre: "CUANDO ME ENAMORO", tipo: "tv", categoria: "novelas" },
    { nombre: "CUIDADO CON EL ANGEL", tipo: "tv", categoria: "novelas" },
    { nombre: "DESPERTAR CONTIGO", tipo: "tv", categoria: "novelas" },
    { nombre: "Devuelveme La Vida", tipo: "tv", categoria: "novelas" },


    { nombre: "Diseñando tu Amor", tipo: "tv", categoria: "novelas" },
    { nombre: "Dulce Ambición", tipo: "tv", categoria: "novelas" },
    { nombre: "El Amor Invencible", tipo: "tv", categoria: "novelas" },
    { nombre: "El Dragon", tipo: "tv", categoria: "novelas" },
    { nombre: "El Juego de las Llaves", tipo: "tv", categoria: "novelas" },
    { nombre: "El Pantanal", tipo: "tv", categoria: "novelas" },
    { nombre: "ENCANTADORAS", tipo: "tv", categoria: "novelas" },
    { nombre: "Eternamente Amándonos", tipo: "tv", categoria: "novelas" },
    { nombre: "HASTA QUE TE CONOCI", tipo: "tv", categoria: "novelas" },
    { nombre: "IMPERIO", tipo: "tv", categoria: "novelas" },
    { nombre: "Isla Brava", tipo: "tv", categoria: "novelas" },
    { nombre: "Jose Jose", tipo: "tv", categoria: "novelas" },
    { nombre: "La Desalmada", tipo: "tv", categoria: "novelas" },
    { nombre: "LA DOÑA", tipo: "tv", categoria: "novelas" },
    { nombre: "La guerrera", tipo: "tv", categoria: "novelas" },
    { nombre: "La Hija Del Mariachi", tipo: "tv", categoria: "novelas" },
    { nombre: "LA LEY DEL CORAZON", tipo: "tv", categoria: "novelas" },
    { nombre: "La Mujer del Diablo", tipo: "tv", categoria: "novelas" },
    { nombre: "La Nieta Elegida", tipo: "tv", categoria: "novelas" },
    { nombre: "LA PATRONA", tipo: "tv", categoria: "novelas" },
    { nombre: "LA PILOTO", tipo: "tv", categoria: "novelas" },
    { nombre: "La Reina Del Flow", tipo: "tv", categoria: "novelas" },
    { nombre: "La Taxista", tipo: "tv", categoria: "novelas" },
    { nombre: "LA TEMPESTAD", tipo: "tv", categoria: "novelas" },
    { nombre: "La Usurpadora", tipo: "tv", categoria: "novelas" },
    { nombre: "La Venganza De Analia", tipo: "tv", categoria: "novelas" },
    { nombre: "La Virgen de La Calle", tipo: "tv", categoria: "novelas" },
    { nombre: "LAS REGLAS DEL JUEGO", tipo: "tv", categoria: "novelas" },
    { nombre: "Los Ricos Tambien Lloran", tipo: "tv", categoria: "novelas" },
    { nombre: "LUZ CLARITA", tipo: "tv", categoria: "novelas" },
    { nombre: "Mentiras Desesperadas", tipo: "tv", categoria: "novelas" },
    { nombre: "Mi Camino es Amarte", tipo: "tv", categoria: "novelas" },
    { nombre: "Mi Corazon Insiste", tipo: "tv", categoria: "novelas" },
    { nombre: "Minas de Pasion", tipo: "tv", categoria: "novelas" },
    { nombre: "Montecristo", tipo: "tv", categoria: "novelas" },
    { nombre: "Mujer de Nadie", tipo: "tv", categoria: "novelas" },
    { nombre: "Nicky Jam El Ganador", tipo: "tv", categoria: "novelas" },
    { nombre: "OLVIDARTE JAMAS", tipo: "tv", categoria: "novelas" },
    { nombre: "Pacto de Sangre", tipo: "tv", categoria: "novelas" },

    { nombre: "PASION", tipo: "tv", categoria: "novelas" },
    { nombre: "Pienso En Ti", tipo: "tv", categoria: "novelas" },
    { nombre: "Romina Poderosa", tipo: "tv", categoria: "novelas" },
    { nombre: "Rubi", tipo: "tv", categoria: "novelas" },
    { nombre: "Segunda Oportunidad", tipo: "tv", categoria: "novelas" },
    { nombre: "Si Nos Dejan", tipo: "tv", categoria: "novelas" },
    { nombre: "Soltero Con Hijas", tipo: "tv", categoria: "novelas" },
    { nombre: "SORTILEGIO", tipo: "tv", categoria: "novelas" },
    { nombre: "SOS Me Estoy Enamorando", tipo: "tv", categoria: "novelas" },
    { nombre: "Tia Alison", tipo: "tv", categoria: "novelas" },
    { nombre: "TIERRA DE REYES", tipo: "tv", categoria: "novelas" },
    { nombre: "Travesía", tipo: "tv", categoria: "novelas" },
    { nombre: "TRIUNFO DEL AMOR", tipo: "tv", categoria: "novelas" },
    { nombre: "Vencer El Desamor", tipo: "tv", categoria: "novelas" },
    { nombre: "VERDADES SECRETAS", tipo: "tv", categoria: "novelas" },
    { nombre: "VIVIR LA VIDA", tipo: "tv", categoria: "novelas" },

    //Peliculas
    { nombre: "Interestelar", tipo: "movie", categoria: "peliculas" },
    { nombre: "Culpa Mia", tipo: "movie", categoria: "peliculas" }

    //Shows
    
     
];
