services:
  - name: chat-backend
    ports:
      - port: 3000
        http: {}
    env:
      - name: PORT
        value: "3000"
      - name: NODE_ENV
        value: production
    regions: ["cdg"]  # París (elige más cercano)
    docker:
      image: node:16-alpine
      cmd: ["npm", "start"]
      args: []
      build:
        commands:
          - npm install